### ISSUE TITLE
Pls add tabs and fix datatime line

### ISSUE THREAD

**Issue by legionpheonix** [bp2008/pingtracer#4]
Thank you very much for your program.
Excellent replacement WinMTR.
There is a request to add tabs, I sometimes need to check several hosts.
Also there is a small visual bug, below in the screenshot.
Maybe it's just me having such a problem on Windows 10 1803 with DPI 125%
![image](https://user-images.githubusercontent.com/25011045/40278066-e587a22c-5c32-11e8-8ee3-831884f1ac05.png)

Add the ability to clean the IP / HOST list
![image](https://user-images.githubusercontent.com/25011045/40278157-7d731142-5c34-11e8-8b9d-ce4a4945dea9.png)

**Comment by bp2008** [comment]
I gave this a try on a tablet I've got running 1803 and set DPI scaling to 125% but the only way I could reproduce the issue you screenshotted is to right-click the exe and go to compatibility settings and change it to let the application handle high-DPI mode.  If you let the system handle high-DPI mode instead, it will have correct layout.

Looks like the alternative would be to increase the minimum required .NET version to 4.7, and I'd probably need to do considerable work on the custom graph controls since they are 100% custom for this app and not the slightest bit high-DPI aware.  I'm just not going to do that any time soon.

**Comment by bp2008** [comment]
Oh and regarding tabs, that isn't going to happen either.  You can enter multiple hosts in the host field (separate them with commas) and each one will get its own ping graph.  This does disable the traceroute, so if you need the traceroute then you need to run multiple instances of the app.  Or go with a more advanced solution like https://www.pingplotter.com/
